#!/bin/bash

if [[ -z $(which aws) ]]; then
  echo "The AWS CLI must be installed on your system: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
  exit 1
else if [[ -z $(which jq) ]]; then
  echo "jq must be installed on your system: https://jqlang.github.io/jq/download/"
  exit 1
else if [[ -z $(which terraform) ]]; then
  echo "terraform must be inastalled on your system: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli"
  exit 1
fi

WORKDIR=$(dirname $(readlink -f $0))
cd $WORKDIR
source .env
rm -rf last_apply.json

terraform apply -auto-approve -json | tee last_apply.json | jq .@message
APPLY_OUTPUT=$(cat last_apply.json)
INSTANCE_ID=$(echo "${APPLY_OUTPUT##*$'\n'}" | jq -r .outputs.instance_id.value)

printf "Awaiting instance start..."
aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID
echo "done"

echo "Getting instance IP..."
INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID | jq -r .Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp)
echo "SOCKS proxy active"
sudo ssh -i ~/.ssh/$TF_VAR_ssh_key_name -q -C -N -p 7153 -o "StrictHostKeyChecking no" -D 666 ec2-user@$INSTANCE_IP

echo "Terminating instance"
aws ec2 terminate-instances --instance-ids $INSTANCE_ID | jq .
echo "Done."
