#!/bin/bash

WORKDIR=$(dirname $(readlink -f $0))
cd $WORKDIR

APPLY_OUTPUT=$(terraform apply -auto-approve -json | tee /dev/tty)
INSTANCE_ID=$(echo "${APPLY_OUTPUT##*$'\n'}" | jq -r .outputs.instance_id.value)

printf "Awaiting instance start..."
aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID
echo "done"

INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID | jq -r .Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp)
echo "SOCKS proxy active"
sudo ssh -i ~/.ssh/$TF_VAR_ssh_key_name -q -C -N -p 7153 -o "StrictHostKeyChecking no" -D 666 ec2-user@$INSTANCE_IP

aws ec2 terminate-instances --instance-ids $INSTANCE_ID | jq .
